import { el } from '../utils/dom.js';

export function renderFaq(container) {
  container.innerHTML = '';

  const faq = el('div', { class: 'faq-view container' },
    el('h2', { class: 'faq-title' }, 'FAQ'),

    faqItem('What does it look like?', null, [
      el('p', {}, 'Here\u2019s what you\u2019ll see after logging in and selecting a playlist:'),
      el('a', { href: 'img/faq-screenshot.png', target: '_blank' },
        el('img', {
          src: 'img/faq-screenshot.png',
          alt: 'Screenshot of Sort Your Music showing a playlist sorted by BPM',
          class: 'faq-screenshot',
        })
      ),
      el('p', { class: 'faq-screenshot-hint' }, 'Click to enlarge'),
    ], true),

    faqItem('How does it work?',
      'Login with Spotify, pick a playlist, click any column header to sort, then save the new order back to Spotify.'),

    faqItem('Does it overwrite my playlist?',
      'Only if you choose "Overwrite Playlist." Otherwise it creates a new copy named after the sort you applied.'),

    faqItem('Is my data safe?',
      'Sort Your Music runs entirely in your browser. Your Spotify credentials are never sent to our server \u2014 authentication uses Spotify\'s own OAuth flow.'),

    faqItem('Privacy Policy', null, [
      el('p', {}, 'Sort Your Music is a client-side web application. There is no server, no database, and no analytics. Nothing leaves your browser.'),

      el('h4', {}, 'What we access'),
      el('p', {}, 'When you log in, Sort Your Music requests the following Spotify OAuth scopes:'),
      el('dl', { class: 'faq-defs' },
        dt('playlist-read-private'), dd('Read your public and private playlists.'),
        dt('playlist-modify-public'), dd('Reorder or save tracks in your public playlists.'),
        dt('playlist-modify-private'), dd('Reorder or save tracks in your private playlists.'),
      ),
      el('p', {}, 'We use these scopes to display your playlists, fetch track audio features (BPM, energy, etc.), and save reordered playlists back to Spotify. We do not access your email, profile details, listening history, or any other Spotify data.'),

      el('h4', {}, 'Data storage'),
      el('p', {}, 'Your Spotify access token is stored in sessionStorage, which is automatically cleared when you close the browser tab. Logging out also clears the token immediately. No cookies, local storage, or server-side storage are used.'),

      el('h4', {}, 'Data sharing'),
      el('p', {}, 'We do not share, sell, or transmit your data to any third party. There is no advertising, no tracking, and no analytics on this site.'),

      el('h4', {}, 'Your control'),
      el('p', {},
        'You can log out at any time to clear your session. To fully revoke access, visit your ',
      ),
      el('a', { href: 'https://www.spotify.com/account/apps/', target: '_blank' }, 'Spotify Apps page'),
      ' and remove Sort Your Music.',

      el('h4', {}, 'Children'),
      el('p', {}, 'Sort Your Music is not directed at children under the age of 13. We do not knowingly collect information from children.'),

      el('h4', {}, 'Spotify\'s privacy policy'),
      el('p', {},
        'Your use of Spotify is also governed by ',
      ),
      el('a', { href: 'https://www.spotify.com/legal/privacy-policy/', target: '_blank' }, 'Spotify\'s Privacy Policy'),
      '.',
    ]),

    faqItem('What do the playlist categories mean?', null, [
      el('dl', { class: 'faq-defs' },
        dt('Mine'), dd('Playlists you created.'),
        dt('Personalized'), dd('Playlists generated by Spotify for you, like Discover Weekly, Daily Mixes, and Release Radar.'),
        dt('Spotify'), dd('Editorial playlists curated by Spotify\u2019s team, such as RapCaviar or Today\u2019s Top Hits.'),
        dt('Others'), dd('Playlists by other users that you\u2019ve added to your library.'),
        dt('Collaborative'), dd('Playlists that multiple people can add tracks to.'),
      ),
    ]),

    faqItem('What are all the sort attributes?', null, [
      el('dl', { class: 'faq-defs' },
        dt('BPM (Tempo)'),
        dd('The estimated tempo of the track in beats per minute. A waltz is around 80 BPM, a pop song around 120, and drum & bass around 170.'),

        dt('Energy'),
        dd('A 0\u2013100 measure of intensity and activity. Energetic tracks feel fast, loud, and noisy \u2014 think death metal. A Bach prelude scores low. Based on dynamic range, perceived loudness, timbre, onset rate, and general entropy.'),

        dt('Danceability'),
        dd('A 0\u2013100 score for how suitable a track is for dancing, based on tempo, rhythm stability, beat strength, and overall regularity.'),

        dt('Loudness'),
        dd('The overall loudness of the track in decibels (dB), averaged across the entire track. Typical values range from \u221260 to 0 dB. Useful for comparing the relative loudness of tracks.'),

        dt('Valence'),
        dd('A 0\u2013100 measure of musical positiveness. High valence tracks sound happy, cheerful, or euphoric, while low valence tracks sound sad, depressed, or angry.'),

        dt('Length'),
        dd('The duration of the track.'),

        dt('Acousticness'),
        dd('A 0\u2013100 confidence score for whether the track is acoustic. 100 means high confidence the track is acoustic.'),

        dt('Popularity'),
        dd('A 0\u2013100 score assigned by Spotify based on the total number of recent plays. Tracks with lots of recent streams score higher. This updates frequently.'),

        dt('Artist Separation'),
        dd('Not a Spotify attribute \u2014 this is computed by Sort Your Music. It rearranges the playlist so that tracks by the same artist are spread as far apart as possible. Sort by this column to avoid hearing the same artist back-to-back.'),

        dt('Random'),
        dd('Assigns a random value to each track for shuffling. Click the column header again to re-shuffle.'),

        dt('Release'),
        dd('The release date of the album the track appears on.'),

        dt('Added'),
        dd('The date the track was added to the playlist.'),
      ),
    ]),

    faqItem('What about podcast episodes?',
      'Playlists can contain podcast episodes alongside music tracks. Episodes appear in the table with italic text and won\u2019t have audio attributes like BPM or energy, since those are only available for music. Episodes are preserved when you save.'),

    faqItem('How was this built?', null, [
      'Using the ',
      el('a', { href: 'https://developer.spotify.com', target: '_blank' }, 'Spotify Web API'),
      ' and ',
      el('a', { href: 'https://claude.ai/claude-code', target: '_blank' }, 'Claude Code'),
      '. The source is on ',
      el('a', { href: 'https://github.com/plamere/SortYourMusic', target: '_blank' }, 'GitHub'),
      '.',
    ]),
  );

  container.appendChild(faq);
}

function dt(text) {
  return el('dt', {}, text);
}

function dd(text) {
  return el('dd', {}, text);
}

function faqItem(question, answerText, answerNodes, open = false) {
  const answer = el('div', { class: 'faq-answer' });
  if (answerNodes) {
    for (const node of answerNodes) {
      answer.append(typeof node === 'string' ? node : node);
    }
  } else {
    answer.textContent = answerText;
  }

  const attrs = { class: 'faq-item' };
  if (open) attrs.open = '';

  return el('details', attrs,
    el('summary', {}, question),
    answer
  );
}
